<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>KovchegVPN</AssemblyName>
    <RootNamespace>KovchegVPN</RootNamespace>
    <StartupObject>KovchegVPN.Program</StartupObject>
    <Product>KovchegVPN</Product>
    <Description>KovchegVPN</Description>
    <Version>1.0.0</Version>
    <ApplicationIcon>Resources\kovcheg.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\logo.png" />
    <EmbeddedResource Include="Resources\kovcheg.ico" />
    <EmbeddedResource Include="Resources\kovcheg_on.ico" />
    <EmbeddedResource Include="Resources\kovcheg_off.ico" />
    <EmbeddedResource Include="Resources\singbox-tun.json" />
    <EmbeddedResource Include="Resources\kovcheg-xray.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
  </ItemGroup>

</Project>
